// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/send-in-chat-message.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageServiceChat_Message_FullMethodName = "/MessageServiceChat/Message"
)

// MessageServiceChatClient is the client API for MessageServiceChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceChatClient interface {
	Message(ctx context.Context, in *NewMessageContentInChat, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type messageServiceChatClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceChatClient(cc grpc.ClientConnInterface) MessageServiceChatClient {
	return &messageServiceChatClient{cc}
}

func (c *messageServiceChatClient) Message(ctx context.Context, in *NewMessageContentInChat, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageServiceChat_Message_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceChatServer is the server API for MessageServiceChat service.
// All implementations must embed UnimplementedMessageServiceChatServer
// for forward compatibility.
type MessageServiceChatServer interface {
	Message(context.Context, *NewMessageContentInChat) (*emptypb.Empty, error)
	mustEmbedUnimplementedMessageServiceChatServer()
}

// UnimplementedMessageServiceChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceChatServer struct{}

func (UnimplementedMessageServiceChatServer) Message(context.Context, *NewMessageContentInChat) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Message not implemented")
}
func (UnimplementedMessageServiceChatServer) mustEmbedUnimplementedMessageServiceChatServer() {}
func (UnimplementedMessageServiceChatServer) testEmbeddedByValue()                            {}

// UnsafeMessageServiceChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceChatServer will
// result in compilation errors.
type UnsafeMessageServiceChatServer interface {
	mustEmbedUnimplementedMessageServiceChatServer()
}

func RegisterMessageServiceChatServer(s grpc.ServiceRegistrar, srv MessageServiceChatServer) {
	// If the following call panics, it indicates UnimplementedMessageServiceChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageServiceChat_ServiceDesc, srv)
}

func _MessageServiceChat_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMessageContentInChat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceChatServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageServiceChat_Message_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceChatServer).Message(ctx, req.(*NewMessageContentInChat))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageServiceChat_ServiceDesc is the grpc.ServiceDesc for MessageServiceChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageServiceChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageServiceChat",
	HandlerType: (*MessageServiceChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Message",
			Handler:    _MessageServiceChat_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/send-in-chat-message.proto",
}
