// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/send-in-ai-message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewMessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageContent) Reset() {
	*x = NewMessageContent{}
	mi := &file_proto_send_in_ai_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageContent) ProtoMessage() {}

func (x *NewMessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_send_in_ai_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageContent.ProtoReflect.Descriptor instead.
func (*NewMessageContent) Descriptor() ([]byte, []int) {
	return file_proto_send_in_ai_message_proto_rawDescGZIP(), []int{0}
}

func (x *NewMessageContent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NewMessageContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewMessageContent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_send_in_ai_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_send_in_ai_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_send_in_ai_message_proto_rawDescGZIP(), []int{1}
}

var File_proto_send_in_ai_message_proto protoreflect.FileDescriptor

const file_proto_send_in_ai_message_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/send-in-ai-message.proto\"a\n" +
	"\x11NewMessageContent\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06roomId\x18\x03 \x01(\tR\x06roomId\"\a\n" +
	"\x05Empty27\n" +
	"\x0eMessageService\x12%\n" +
	"\aMessage\x12\x12.NewMessageContent\x1a\x06.EmptyB#Z!github.com/pasaz/ChipiAi/proto;pbb\x06proto3"

var (
	file_proto_send_in_ai_message_proto_rawDescOnce sync.Once
	file_proto_send_in_ai_message_proto_rawDescData []byte
)

func file_proto_send_in_ai_message_proto_rawDescGZIP() []byte {
	file_proto_send_in_ai_message_proto_rawDescOnce.Do(func() {
		file_proto_send_in_ai_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_send_in_ai_message_proto_rawDesc), len(file_proto_send_in_ai_message_proto_rawDesc)))
	})
	return file_proto_send_in_ai_message_proto_rawDescData
}

var file_proto_send_in_ai_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_send_in_ai_message_proto_goTypes = []any{
	(*NewMessageContent)(nil), // 0: NewMessageContent
	(*Empty)(nil),             // 1: Empty
}
var file_proto_send_in_ai_message_proto_depIdxs = []int32{
	0, // 0: MessageService.Message:input_type -> NewMessageContent
	1, // 1: MessageService.Message:output_type -> Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_send_in_ai_message_proto_init() }
func file_proto_send_in_ai_message_proto_init() {
	if File_proto_send_in_ai_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_send_in_ai_message_proto_rawDesc), len(file_proto_send_in_ai_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_send_in_ai_message_proto_goTypes,
		DependencyIndexes: file_proto_send_in_ai_message_proto_depIdxs,
		MessageInfos:      file_proto_send_in_ai_message_proto_msgTypes,
	}.Build()
	File_proto_send_in_ai_message_proto = out.File
	file_proto_send_in_ai_message_proto_goTypes = nil
	file_proto_send_in_ai_message_proto_depIdxs = nil
}
