// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/send-in-ai-message-response.proto

package responsepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageServiceResponse_Message_FullMethodName = "/MessageServiceResponse/Message"
)

// MessageServiceResponseClient is the client API for MessageServiceResponse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceResponseClient interface {
	Message(ctx context.Context, in *NewMessageContentResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type messageServiceResponseClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceResponseClient(cc grpc.ClientConnInterface) MessageServiceResponseClient {
	return &messageServiceResponseClient{cc}
}

func (c *messageServiceResponseClient) Message(ctx context.Context, in *NewMessageContentResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageServiceResponse_Message_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceResponseServer is the server API for MessageServiceResponse service.
// All implementations must embed UnimplementedMessageServiceResponseServer
// for forward compatibility.
type MessageServiceResponseServer interface {
	Message(context.Context, *NewMessageContentResponse) (*emptypb.Empty, error)
	mustEmbedUnimplementedMessageServiceResponseServer()
}

// UnimplementedMessageServiceResponseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceResponseServer struct{}

func (UnimplementedMessageServiceResponseServer) Message(context.Context, *NewMessageContentResponse) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Message not implemented")
}
func (UnimplementedMessageServiceResponseServer) mustEmbedUnimplementedMessageServiceResponseServer() {
}
func (UnimplementedMessageServiceResponseServer) testEmbeddedByValue() {}

// UnsafeMessageServiceResponseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceResponseServer will
// result in compilation errors.
type UnsafeMessageServiceResponseServer interface {
	mustEmbedUnimplementedMessageServiceResponseServer()
}

func RegisterMessageServiceResponseServer(s grpc.ServiceRegistrar, srv MessageServiceResponseServer) {
	// If the following call panics, it indicates UnimplementedMessageServiceResponseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageServiceResponse_ServiceDesc, srv)
}

func _MessageServiceResponse_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMessageContentResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceResponseServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageServiceResponse_Message_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceResponseServer).Message(ctx, req.(*NewMessageContentResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageServiceResponse_ServiceDesc is the grpc.ServiceDesc for MessageServiceResponse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageServiceResponse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageServiceResponse",
	HandlerType: (*MessageServiceResponseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Message",
			Handler:    _MessageServiceResponse_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/send-in-ai-message-response.proto",
}
