// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/ai-callback.proto

package callbackpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiCallback_SendAiMessage_FullMethodName = "/AiCallback/SendAiMessage"
)

// AiCallbackClient is the client API for AiCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiCallbackClient interface {
	SendAiMessage(ctx context.Context, in *AiMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type aiCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewAiCallbackClient(cc grpc.ClientConnInterface) AiCallbackClient {
	return &aiCallbackClient{cc}
}

func (c *aiCallbackClient) SendAiMessage(ctx context.Context, in *AiMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AiCallback_SendAiMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiCallbackServer is the server API for AiCallback service.
// All implementations must embed UnimplementedAiCallbackServer
// for forward compatibility.
type AiCallbackServer interface {
	SendAiMessage(context.Context, *AiMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedAiCallbackServer()
}

// UnimplementedAiCallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiCallbackServer struct{}

func (UnimplementedAiCallbackServer) SendAiMessage(context.Context, *AiMessage) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAiMessage not implemented")
}
func (UnimplementedAiCallbackServer) mustEmbedUnimplementedAiCallbackServer() {}
func (UnimplementedAiCallbackServer) testEmbeddedByValue()                    {}

// UnsafeAiCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiCallbackServer will
// result in compilation errors.
type UnsafeAiCallbackServer interface {
	mustEmbedUnimplementedAiCallbackServer()
}

func RegisterAiCallbackServer(s grpc.ServiceRegistrar, srv AiCallbackServer) {
	// If the following call panics, it indicates UnimplementedAiCallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiCallback_ServiceDesc, srv)
}

func _AiCallback_SendAiMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiCallbackServer).SendAiMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiCallback_SendAiMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiCallbackServer).SendAiMessage(ctx, req.(*AiMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AiCallback_ServiceDesc is the grpc.ServiceDesc for AiCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AiCallback",
	HandlerType: (*AiCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAiMessage",
			Handler:    _AiCallback_SendAiMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai-callback.proto",
}
