// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/ai-callback.proto

package callbackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AiMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiMessage) Reset() {
	*x = AiMessage{}
	mi := &file_proto_ai_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiMessage) ProtoMessage() {}

func (x *AiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiMessage.ProtoReflect.Descriptor instead.
func (*AiMessage) Descriptor() ([]byte, []int) {
	return file_proto_ai_callback_proto_rawDescGZIP(), []int{0}
}

func (x *AiMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AiMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AiMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_proto_ai_callback_proto protoreflect.FileDescriptor

const file_proto_ai_callback_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ai-callback.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\tAiMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06roomId\x18\x03 \x01(\tR\x06roomId2A\n" +
	"\n" +
	"AiCallback\x123\n" +
	"\rSendAiMessage\x12\n" +
	".AiMessage\x1a\x16.google.protobuf.EmptyB+Z)github.com/pasaz/ChipiAi/proto;callbackpbb\x06proto3"

var (
	file_proto_ai_callback_proto_rawDescOnce sync.Once
	file_proto_ai_callback_proto_rawDescData []byte
)

func file_proto_ai_callback_proto_rawDescGZIP() []byte {
	file_proto_ai_callback_proto_rawDescOnce.Do(func() {
		file_proto_ai_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_callback_proto_rawDesc), len(file_proto_ai_callback_proto_rawDesc)))
	})
	return file_proto_ai_callback_proto_rawDescData
}

var file_proto_ai_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ai_callback_proto_goTypes = []any{
	(*AiMessage)(nil),     // 0: AiMessage
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_proto_ai_callback_proto_depIdxs = []int32{
	0, // 0: AiCallback.SendAiMessage:input_type -> AiMessage
	1, // 1: AiCallback.SendAiMessage:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_callback_proto_init() }
func file_proto_ai_callback_proto_init() {
	if File_proto_ai_callback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_callback_proto_rawDesc), len(file_proto_ai_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_callback_proto_goTypes,
		DependencyIndexes: file_proto_ai_callback_proto_depIdxs,
		MessageInfos:      file_proto_ai_callback_proto_msgTypes,
	}.Build()
	File_proto_ai_callback_proto = out.File
	file_proto_ai_callback_proto_goTypes = nil
	file_proto_ai_callback_proto_depIdxs = nil
}
